version: '2.4'

services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: climate-red
  #
  # adminer:
  #   image: adminer:4
  #   ports:
  #     - 8080:8080
